### PR TITLE
updating deps by hand to bump vscode engine

### PR DESCRIPTION
**Pull request by bfitzpat**
Signed-off-by: bfitzpat@redhat.com <bfitzpat@redhat.com>

### CODE REVIEW

**Comment by bfitzpat** [comment]
This will replace https://github.com/camel-tooling/vscode-wsdl2rest/pull/224, https://github.com/camel-tooling/vscode-wsdl2rest/pull/225, and https://github.com/camel-tooling/vscode-wsdl2rest/pull/226 and take care of the vscode engine version bump.

**Comment by apupier** [comment]
149 tests are failing, removing the "ready to review flag"

**Comment by bfitzpat** [comment]
Everything passes locally. Not sure why it's exploding. Will look

**Comment by bfitzpat** [comment]
@djelinek can you see any reason why all the wsdl2rest UI tests are failing on travis? our unit tests pass fine. was there an update to vscode-extension-tester or vscode-uitests-tooling by chance?

**Comment by djelinek** [comment]
Hi, yes. problem is new vscode version 1.44 it seems that something changed and it needs to be fixed at vscode-extension-tester level.. then update of tester dependency should fix it

**Comment by bfitzpat** [comment]
Thanks @djelinek ! Let us know when we have a new version and we'll update this PR to pull it in

**Comment by apupier** [comment]
given the error stack, I'm nto sure that it is related to UI framework:

```
[ERROR] *************************************
[ERROR] Error occurred while running main from: org.apache.camel.spring.Main
[ERROR] 
java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.apache.camel.maven.RunMojo$1.run (RunMojo.java:519)
    at java.lang.Thread.run (Thread.java:748)
Caused by: org.springframework.beans.factory.BeanDefinitionStoreException: Could not resolve bean definition resource pattern [META-INF/spring/*.xml]; nested exception is java.io.FileNotFoundException: class path resource [META-INF/spring/] cannot be resolved to URL because it does not exist
    at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions (AbstractBeanDefinitionReader.java:229)
    at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions (AbstractBeanDefinitionReader.java:188)
    at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions (AbstractBeanDefinitionReader.java:252)
    at org.springframework.context.support.AbstractXmlApplicationContext.loadBeanDefinitions (AbstractXmlApplicationContext.java:127)
    at org.springframework.context.support.AbstractXmlApplicationContext.loadBeanDefinitions (AbstractXmlApplicationContext.java:93)
    at org.springframework.context.support.AbstractRefreshableApplicationContext.refreshBeanFactory (AbstractRefreshableApplicationContext.java:129)
    at org.springframework.context.support.AbstractApplicationContext.obtainFreshBeanFactory (AbstractApplicationContext.java:614)
    at org.springframework.context.support.AbstractApplicationContext.refresh (AbstractApplicationContext.java:514)
    at org.springframework.context.support.ClassPathXmlApplicationContext.<init> (ClassPathXmlApplicationContext.java:139)
    at org.springframework.context.support.ClassPathXmlApplicationContext.<init> (ClassPathXmlApplicationContext.java:93)
    at org.apache.camel.spring.Main.createDefaultApplicationContext (Main.java:222)
    at org.apache.camel.spring.Main.doStart (Main.java:154)
    at org.apache.camel.support.ServiceSupport.start (ServiceSupport.java:61)
    at org.apache.camel.main.MainSupport.run (MainSupport.java:170)
    at org.apache.camel.main.MainSupport.run (MainSupport.java:501)
    at org.apache.camel.spring.Main.main (Main.java:86)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.apache.camel.maven.RunMojo$1.run (RunMojo.java:519)
    at java.lang.Thread.run (Thread.java:748)
Caused by: java.io.FileNotFoundException: class path resource [META-INF/spring/] cannot be resolved to URL because it does not exist
    at org.springframework.core.io.ClassPathResource.getURL (ClassPathResource.java:187)
    at org.springframework.core.io.support.PathMatchingResourcePatternResolver.findPathMatchingResources (PathMatchingResourcePatternResolver.java:493)
    at org.springframework.core.io.support.PathMatchingResourcePatternResolver.getResources (PathMatchingResourcePatternResolver.java:294)
    at org.springframework.context.support.AbstractApplicationContext.getResources (AbstractApplicationContext.java:1297)
    at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions (AbstractBeanDefinitionReader.java:216)
    at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions (AbstractBeanDefinitionReader.java:188)
    at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions (AbstractBeanDefinitionReader.java:252)
    at org.springframework.context.support.AbstractXmlApplicationContext.loadBeanDefinitions (AbstractXmlApplicationContext.java:127)
    at org.springframework.context.support.AbstractXmlApplicationContext.loadBeanDefinitions (AbstractXmlApplicationContext.java:93)
    at org.springframework.context.support.AbstractRefreshableApplicationContext.refreshBeanFactory (AbstractRefreshableApplicationContext.java:129)
    at org.springframework.context.support.AbstractApplicationContext.obtainFreshBeanFactory (AbstractApplicationContext.java:614)
    at org.springframework.context.support.AbstractApplicationContext.refresh (AbstractApplicationContext.java:514)
    at org.springframework.context.support.ClassPathXmlApplicationContext.<init> (ClassPathXmlApplicationContext.java:139)
    at org.springframework.context.support.ClassPathXmlApplicationContext.<init> (ClassPathXmlApplicationContext.java:93)
    at org.apache.camel.spring.Main.createDefaultApplicationContext (Main.java:222)
    at org.apache.camel.spring.Main.doStart (Main.java:154)
    at org.apache.camel.support.ServiceSupport.start (ServiceSupport.java:61)
    at org.apache.camel.main.MainSupport.run (MainSupport.java:170)
    at org.apache.camel.main.MainSupport.run (MainSupport.java:501)
    at org.apache.camel.spring.Main.main (Main.java:86)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.apache.camel.maven.RunMojo$1.run (RunMojo.java:519)
    at java.lang.Thread.run (Thread.java:748)
[ERROR] *************************************
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  3.992 s
[INFO] Finished at: 2020-04-09T15:48:07Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.camel:camel-maven-plugin:2.21.0.fuse-750033-redhat-00001:run (default-cli) on project example: null: MojoExecutionException: InvocationTargetException: Could not resolve bean definition resource pattern [META-INF/spring/*.xml]; nested exception is java.io.FileNotFoundException: class path resource [META-INF/spring/] cannot be resolved to URL because it does not exist -> [Help 1]
```

**Comment by apupier** [comment]
ok, same error on other PR such as https://travis-ci.org/github/camel-tooling/vscode-wsdl2rest/builds/672854212 so should be a side effect of it

**Comment by bfitzpat** [comment]
I attempted to reset the version locally as I saw with https://github.com/camel-tooling/camel-lsp-client-vscode/pull/305/ and I see this: `Unable to install extension 'redhat.vscode-wsdl2rest' as it is not compatible with VS Code '1.43.2'.`

```
nstalling extensions...
Unable to install extension 'redhat.vscode-wsdl2rest' as it is not compatible with VS Code '1.43.2'.
Failed Installing Extensions: /home/bfitzpat/github/vscode-wsdl2rest/vscode-wsdl2rest-0.0.12.vsix
(node:25006) UnhandledPromiseRejectionWarning: Error: Command failed: ELECTRON_RUN_AS_NODE=1 "/home/bfitzpat/github/vscode-wsdl2rest/test-resources/VSCode-linux-x64/code" "/home/bfitzpat/github/vscode-wsdl2rest/test-resources/VSCode-linux-x64/resources/app/out/cli.js" --install-extension "/home/bfitzpat/github/vscode-wsdl2rest/vscode-wsdl2rest-0.0.12.vsix"
    at checkExecSyncError (child_process.js:630:11)
    at Object.execSync (child_process.js:666:15)
    at CodeUtil.installExtension (/home/bfitzpat/github/vscode-wsdl2rest/node_modules/vscode-extension-tester/out/util/codeUtil.js:112:23)
    at ExTester.<anonymous> (/home/bfitzpat/github/vscode-wsdl2rest/node_modules/vscode-extension-tester/out/extester.js:107:30)
    at Generator.next (<anonymous>)
    at /home/bfitzpat/github/vscode-wsdl2rest/node_modules/vscode-extension-tester/out/extester.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/home/bfitzpat/github/vscode-wsdl2rest/node_modules/vscode-extension-tester/out/extester.js:4:12)
    at ExTester.installVsix (/home/bfitzpat/github/vscode-wsdl2rest/node_modules/vscode-extension-tester/out/extester.js:86:16)
    at ExTester.<anonymous> (/home/bfitzpat/github/vscode-wsdl2rest/node_modules/vscode-extension-tester/out/extester.js:135:24)
(node:25006) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:25006) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by apupier** [comment]
> Unable to install extension 'redhat.vscode-wsdl2rest' as it is not compatible with VS Code '1.43.2'

When do you hit that? When starting test or launching an instance from VS Code? have you upgraded your local VS Code to latest version 1.44.0? or it is still on 1.43.2?

**Comment by bfitzpat** [comment]
> When do you hit that? When starting test or launching an instance from VS Code? have you upgraded your local VS Code to latest version 1.44.0? or it is still on 1.43.2?

command line: npm run ui-test 
devdependencies and engine are set to 1.44.0 for vscode

**Comment by apupier** [comment]
> > When do you hit that? When starting test or launching an instance from VS Code? have you upgraded your local VS Code to latest version 1.44.0? or it is still on 1.43.2?
> 
> command line: npm run ui-test
> devdependencies and engine are set to 1.44.0 for vscode

for ui-test, it should pick the 1.44.0 version by default. Unless the script is modified locally with `--code_version 1.43.2` as here https://github.com/camel-tooling/vscode-wsdl2rest/pull/229/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R68

This PR and the pointed one are not compatible

**Comment by bfitzpat** [comment]
> for ui-test, it should pick the 1.44.0 version by default. Unless the script is modified locally with `--code_version 1.43.2` as here https://github.com/camel-tooling/vscode-wsdl2rest/pull/229/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R68
> 
> This PR and the pointed one are not compatible

Apparently I need to clarify to connect the dots. 

1) Yes, I am aware 1.44.0 does not currently work with the vscode-extension-tester
2) I saw the `--code_version 1.43.2` fix in https://github.com/camel-tooling/camel-lsp-client-vscode/pull/305 and attempted it locally
3) Running `npm run ui-test` locally with no vscode instance running on the system beforehand fails with the errors reported in https://github.com/camel-tooling/vscode-wsdl2rest/pull/227#issuecomment-613463060
4) I have now updated this PR to include the change and all tests initially seem to run on travis.ci, but when I look at the log I see the same issues with the ui-test failure reported there. Not sure why the build isn't reported as a failure if the ui tests fail.

This adjustment to always use the latest version of vscode obviously has a few issues, though they aren't insurmountable. I know QE is working on the vscode-extension-tester issue and we'll get it resolved and can move forward.

**Comment by apupier** [comment]
> 4\. Not sure why the build isn't reported as a failure if the ui tests fail.

vscode-extension-tester issue, I reported https://github.com/redhat-developer/vscode-extension-tester/issues/98

**Comment by bfitzpat** [comment]
This was handled through the other dependabot PRs

**Pull request closed without merging**
