### PR TITLE
issue #16 - cleaning up test code

### PR DESCRIPTION
**Pull request by bfitzpat**
Signed-off-by: Brian Fitzpatrick <bfitzpat@redhat.com>

### CODE REVIEW

**Comment by lhein** [comment]
Why not just use the fs-extra module? It provides everything fs already has and add additional useful stuff like recursive deletion of files / folders. See https://www.npmjs.com/package/fs-extra.

**Comment by apupier** [comment]
seems fs-extra (12.9M downloads/21.9k dependents) is more used than del (6.7M/3k dependents). they both use rimraf under the hood for deletion.
I pointed to del as it was focused on just the del and that i don't know the npm ecosystem well. Using fs-extra seems better to use as more commonly used. Sorry to have pointed to del direction.

**Comment by lhein** [comment]
I think there is no wrong and right here. It was just a suggestion to use the more widely used module.

**Comment by bfitzpat** [comment]
@lhein and @apupier - I didn't know the fs-extra package had the remove capability and it was already being used in the project, so I have modified the PR to remove the del package and just use fs-extra

**Pull request merged**
